### ISSUE TITLE
add key psk

### ISSUE THREAD

**Issue by Vincenzoferrara** [jarnoaxel/python-wireguard#27]
to install wireguard on the server I used the pivpn script, which can also generate users and includes the psk key.
how do i enter the key?

**Comment by jarnoaxel** [comment]
Hello  @Vincenzoferrara, thank you for your question. At the moment, this library does not support pre-shared keys. This is because the library was developed as part of a project for adding anonymous authentication to Wireguard, and pre-shared keys 'undo' the benefits offered by anonymous authentication (they always belong to the same user). The goal was to have a simple way for generating new keys and adding new peers, to have clients use disposable one-time use key pairs and then adding the anonymous authentication on top of that.

However, you probably have a completely different use case than I did so then it's probably nice to be able to use pre-shared keys. If there is more demand for it I can add support, just need to find the time! Also, what is your use case exactly? Because Wireguard can be sufficient with just the asymmetrical key pairs and no psk so you may not need it after all.

**Comment by Vincenzoferrara** [comment]
i use wireguard to connect to a database (mariadb) on my local network

and i thought it was a "simple" api to connect to wireguard (i just started coding)
I think you should add this information to the readme

**Comment by jarnoaxel** [comment]
Aha I see. Just using public/private key pairs should suffice for your use case (also it is not very common to use PSKs with Wireguard at all) so you can use my library. Simple is relative, this is meant to make it easier to automate certain Wireguard tasks when you need to use it as part of an application you are developing, for instance if you are developing a VPN client/server software based on Wireguard. It does, however, require that you are comfortable manually setting up Wireguard in the first place, and not meant as an alternative for that. Simple as in "makes it easier to integrate Wireguard into a python application you are developing", not simple as in "makes it easier to use Wireguard itself".

That aside, and onto the problem you are describing:

I have not used pivpn myself, but I assume you use it to configure the server side. I am not sure where and how you generate the client-side key pairs (you should also do this on the client machine for security reasons, there's no need for the server-side to have access to your user's private key), but you could of course use this as well. If you look at the readme, then at [Client](https://github.com/jarnoaxel/python-wireguard#client) you should see how to connect to your server. Assuming you know the public IP address and port where your VPN server is located, the client IP address you have configured for your client using pivpn and the public key of the server.

If you do not generate the client-side key pair using `python-wireguard` but instead have those generated somewhere else, you can create the client class as follows:

```python
from python_wireguard import Client, ServerConnection, Key

local_ip = "the configured local IP (within the VPN, that is) for this client, including CIRD block" # (so like 10.0.0.2/24 for instance)
private_key = Key("the wireguard private key of the client (in base64 format)")

client = Client('wg-client', private_key, local_ip)

srv_key = Key("the wireguard public key of the server (in base64 format)")
endpoint = "public ip address of the server"
port = 51820 # The port on which the server has been set up to listen, the one I entered is the default

server_conn = ServerConnection(srv_key, endpoint, port)

client.set_server(server_conn)
client.connect()
```

Be sure to run this script as root, otherwise it cannot alter your network interface settings to configure Wireguard. Also, this only works on Linux (should say so in the readme).

## Other important considerations
You say that the purpose of the VPN usage is so that you can connect to a mariadb database server on your local network. So then I assume that your VPN server will also be inside of this local network. If you want to be able to connect to it, you should make sure that the port it listens on for wireguard connections (51820 by default) is forwarded to the device running the wireguard server (or that it is in some other way accessible), otherwise you will not be able to connect to it. 

Another thing is that you may not need programmatic access to Wireguard at all (using this library or another one), as it sounds like you are just setting up a single connection (though I do not know for sure, you have provided very limited information so I don't know what it is that is trying to connect to mariadb, is it a web app that does so or are you trying to connect using a mysql client to view the information in it yourself?), there may be other options for this. You could also just manually configure the Wireguard connection (or use my example scripts in the readme for both ends of the connection).

I hope this helps or points you in the right direction, and good luck. If you have any questions feel free to ask, I'd like to help but then please supply a bit more information. Also sorry if I'm over-explaining a bit, I don't know exactly how much knowledge "i just started coding" means, or how much knowledge you have about Wireguard in general.

**Comment by Vincenzoferrara** [comment]
thanks for all the help you are giving me.

more or less in 2016 I started to create a management system with windows form (net framework) as my first project, which connected to mysql.

every now and then I improve some code since then (but only free time)
now this management system connects to maradb as a database and to a nas for photos, both on the same network (but on 2 separate machines)

I also recently installed wireguard, to connect remotely, I opened ports, and everything needed to make it work (from a smartphone it works perfectly)
  the reason i chose pivpn and that it allows you to:
- create users by entering only the name
- it also automatically generates the connection file for the client
- can block or delete users, specifying only the untete name
all this works only on linux (it too and another pc)

nas, mariadb and wireguard are all virtual machines, on a pc with proxmox

I switched to linux on my main pc a few days ago, which is why I decided to use pyton (it's the first time I've used it), because it's much more cross-platform, and also because there are no wireguard libraries on windows

now the questions are:
- is this library compatible with windows? (of course I know I can't use it in c#, even though there is a library called pyton.net)
- is there any way to see if the connection works, or do I have to integrate it myself?
- is it possible to specify the dns as well? (I have another vm with pi-hole which, in addition to blocking ads, gives the nas and database a name)

here is the code i am using to connect to wireguard:

```
from python_wireguard import Client, ServerConnection, Key
import os

name_conncetion = "wg_client" #name interface
local_ip = "10.75.205.3/24" 
public_key = Key("")
private_key = Key("")
endpoint = "192.168.1.22" #ip or name server
port = 51820
dns = "192.168.1.3"

client = Client(name_conncetion, private_key, local_ip)
server_conn = ServerConnection(public_key, endpoint, port)

client.set_server(server_conn)
client.connect()


os.system("wg show")
```
for testing I use the local network, and I deleted the keys before sending
sorry for the too long message
